spring:
    datasource:
      url: jdbc:h2:file:./database/localdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
      initialization-mode: always
      continue-on-error: true
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false